const ACTIONS = {

    REGISTER: {
        USER_REGISTRATION_PENDING: "USER_REGISTRATION_PENDING",
        USER_REGISTRATION_SUCCESS: "USER_REGISTRATION_SUCCESS",
        USER_REGISTRATION_FAILED: "USER_REGISTRATION_FAILED",
    }

}
export default ACTIONS;